openapi: 3.0.2

info:
  version: 0.0.2
  title: Hackernews Mock API
  description: Mock API

paths:
  /api/news:
    get:
      operationId: hackernews.api.news.list_news
      summary: Returns the latest news
      tags:
        - News

      responses:
        200:
          description: The lastest news
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: array
                    items:
                      $ref: '#/components/schemas/News'

components:
  schemas:
    Author:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: John Doe
        username:
          type: string
          example: johndoe
        avatar:
          type: string
          example: http://example.com/img/avatar/jose_thumb.png
          nullable: true

    News:
      type: object
      properties:
        id:
          type: integer
          example: 42
        title:
          type: string
          example: Python is a great option for backend and APIs
        description:
          type: string
          example: This is along text within more detailed information about the news
          nullable: true
        author:
          $ref: '#/components/schemas/Author'
        comments_count:
          type: integer
          example: 1
          nullable: true
        comments:
          type: array
          nullable: true
          items:
            $ref: '#/components/schemas/Comment'
        created_at:
          type: string
          format: date-time
          example: 2021-01-11T11:32:28Z

    Comment:
      type: object
      properties:
        id:
          type: integer
          example: 100
        text:
          type: string
          example: This is an awesome news
        created_at:
          type: string
          format: date-time
          example: 2021-01-11T11:32:28Z
